spring:
  profiles.active: develop
---
spring:
  profiles: develop
  dataSource:
        driver-class-name: org.sqlite.JDBC
        url: jdbc:sqlite:target/eec-test.db
        username: root
        password: root

---
excel:
  creator: guanquan.wang
  company: cn.ttzero
  storage:
    path: ./excel