spring:
  profiles.active: develop
---
spring:
  profiles: develop
  dataSource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/eec?useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root

---
excel:
  creator: guanquan.wang
  storage:
    path: ./excel